//OPERADERES MATEMATICOS
// + - * / %

let numUNO = 50;
let numDos = 10;

let resultado;

resultado = numUNO + numDos
// El signo + se utiliza para concatenar datos de tipo string
console.log(numUno + numDos);
console.log(resultado);

// resta
resultado = numUNO - numDos
 
console.log("el resultado de la resta es: " + resultado);

// division
 resultado = numUNO / numDos

 console.log("el resultado de la division es: " + resultado);

 //multiplicacion
 resultado = numUNO * numDos
 console.log("el resultado de la multiplicacion es: " + resultado);

 //modulo
 resultado = numUNO % numDos
 console.log("el resultado del modulo es: " + resultado);

//Ejemplo de lenguaje estatico
//Java
/* int edad = 20 */

//typescrip
/* edad: Number = 21; */