

// ESTOS SON LOS COMENTARIOS DE UNA SOLA LINEA EN JS

/*  
COMENTARIOS 
DE VARIAS 
LINEAS 
EN JS
*/

console.log('3. Estoy en el archivo de JS');

// Variables: espacios de memoria para almacenar los datos
// 1. var:
// Palabras reservadas: son utilizadas solo para las definiciones del lenguaje de programacion
var nombre; //caracter/letras
var Email
var edad
var pais

/*   //NO
var 12345;
var nombre apellido;
var =pais;
var -edad;
*/

//si
var $provincia;
var nombreApellido; //camelcase
var nombre_apellido; //underscore

let provincia;

//const representa una constante: NO CAMBIA EN LA EJECUCION DEL PROGRAMA

//ESTO ES UNA DECLARACION DE UNA VARIABLEY ASIGNACION DE UN VALOR
const DNI = 44873759;

nombre = 'Matias'
apellido = 'Villalba'
//= REPRESENTA ASIGNACION DE DATOS


provincia = 'Buenos Aires'; //string

provincia = 'Cordoba';

provincia = 'Mendoza';

provincia = 15; //numeros - int

provincia = true; //boolean

provincia = false;

//funciones
console.log( nombre + apellido + provincia)
console.error(nombre + apellido + provincia)
console.warn(nombre + apellido + provincia);

alert('soy un mensaje de alerta al cliente')
